# Generated by Django 6.0.3 on 2026-03-14 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0002_dynamicform_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ticket',
            name='change_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('NORMAL', 'Normal'), ('EMERGENCY', 'Emergency')], max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='impact',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('BREACHED', 'Breached')], default='ON_TRACK', max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CabMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.ManyToManyField(blank=True, related_name='cab_meetings', to='itsm.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('fulfillment_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='itsm.dynamicform')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLING', 'Fulfilling'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SUBMITTED', max_length=16)),
                ('variables', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_catalog_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='itsm.catalogitem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_requests', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_request', to='itsm.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='KnownError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.TextField(blank=True)),
                ('workaround', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='known_error', to='itsm.ticket')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='known_errors', to='itsm.knowledgearticle')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SLA', 'SLA'), ('APPROVAL', 'Approval'), ('INFO', 'Info'), ('AI', 'AI')], default='INFO', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='itsm.team')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='affected_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='itsm.service'),
        ),
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INCIDENT', 'Incident'), ('SERVICE_REQUEST', 'Service Request'), ('PROBLEM', 'Problem'), ('CHANGE', 'Change')], max_length=32)),
                ('priority', models.CharField(choices=[('P1', 'P1 - Critical'), ('P2', 'P2 - High'), ('P3', 'P3 - Medium'), ('P4', 'P4 - Low')], max_length=2)),
                ('resolution_minutes', models.PositiveIntegerField(default=480)),
                ('at_risk_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'priority'), name='unique_sla_policy_kind_priority')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('helpful', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='itsm.knowledgearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'user'), name='unique_feedback_per_article_user')],
            },
        ),
        migrations.CreateModel(
            name='ServiceRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rel_type', models.CharField(choices=[('DEPENDS_ON', 'Depends On'), ('RUNS_ON', 'Runs On')], default='DEPENDS_ON', max_length=16)),
                ('source_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='itsm.service')),
                ('target_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_relationships', to='itsm.asset')),
                ('target_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='itsm.service')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('target_service__isnull', False), ('target_asset__isnull', False), _connector='OR'), name='service_relationship_requires_target')],
            },
        ),
    ]
