# Generated by Django 6.0.3 on 2026-03-14 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0003_ticket_breached_at_ticket_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('guest_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slack_webhook_url', models.CharField(blank=True, max_length=500)),
                ('teams_webhook_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_war_rooms', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='war_room', to='itsm.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='WarRoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='itsm.warroommessage')),
                ('war_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='itsm.warroom')),
            ],
        ),
        migrations.CreateModel(
            name='WarRoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('FACILITATOR', 'Facilitator'), ('AGENT', 'Agent'), ('OBSERVER', 'Observer'), ('GUEST', 'Guest')], default='AGENT', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('war_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='itsm.warroom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('war_room', 'user'), name='unique_war_room_participant_user')],
            },
        ),
    ]
