# Generated by Django 6.0.3 on 2026-03-14 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0007_assettransaction_barcodetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=16)),
                ('message', models.CharField(max_length=300)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='itsm.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('cpu_pct', models.FloatField(blank=True, null=True)),
                ('memory_pct', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='itsm.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', '-captured_at'], name='itsm_assetm_asset_i_2d861a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='itsm.asset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'kind'), name='unique_recommendation_kind_per_asset')],
            },
        ),
    ]
